apiVersion: apps/v1
kind: Deployment
metadata:
    name: nifi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nifi
    template:
        metadata:
            labels:
                app: nifi
        spec:
            containers:
                - name: nifi
                  image: apache/nifi
                  ports:
                      - containerPort: 8443
                  env:
                      - name: NIFI_WEB_HTTP_PORT
                        value: 8443